# Generated by Django 4.2.27 on 2026-01-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.CharField(max_length=200, verbose_name='входные данные')),
                ('output_data', models.CharField(max_length=200, verbose_name='выходные данные')),
            ],
        ),
    ]
